This file contains the code to find the most suitable K value for the KNN filling algorithm
Since Logistic regression performs and worst among all algorithm, we don't use it here

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sklearn
# Cross Validation Classification Accuracy
from pandas import read_csv
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import statsmodels.api as sm
from sklearn import preprocessing 
from sklearn.impute import KNNImputer
# from sklearn.neighbors import KNeighborsClassifier
#import faiss
from numpy import isnan
#import matplotlib.pyplot as plot
from matplotlib import pyplot
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,f1_score
from sklearn import tree
import statistics
import time
import warnings
warnings.filterwarnings('ignore')
# plotting errorbar graph for visual representation of the performance of the classifiers
import matplotlib.pyplot as plt
from matplotlib.transforms import Affine2D
import random
from xgboost import XGBClassifier
import shutil
import os
from os import path
import multiprocessing as mp
from concurrent.futures import ProcessPoolExecutor
import ipynb.fs.full.our_functions_library as flib
from our_evaluate_sepsis_score import evaluate_performance
#from our_functions_library import *

In [2]:
# Global initialization, get all the data from file and generate all the needed variable
filename = 'raw_data/raw_data_1000.csv' # use raw dataset
#filename = 'data.csv' # use raw dataset
originalData = read_csv(filename) # read csv data into DataFrame var raw
print("Data size:",originalData.shape)
Original_Uniq_ID= np.unique(originalData['Patient_id']) 
Uniq_ID = Original_Uniq_ID.copy()
print('Patient id size:',len(Uniq_ID))
X_columns = ['HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2','BaseExcess', 'HCO3', 'FiO2', 'pH', 
             'PaCO2', 'SaO2', 'AST', 'BUN','Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct',
             'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium','Bilirubin_total', 'TroponinI', 'Hct', 
             'Hgb', 'PTT', 'WBC','Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2','HospAdmTime',
             'ICULOS', 'Patient_id', 'time']
y_columns = ['Patient_id', 'SepsisLabel']

# To test if these 3 columns is useful
# originalData = originalData.drop(['Unit1', 'Unit2', 'EtCO2'], axis=1)
# X_columns.remove('Unit1')
# X_columns.remove( 'Unit2')
# X_columns.remove( 'EtCO2')

# Initialize the empty array X_train, X_test, y_train, y_test
X_train = pd.DataFrame(columns = X_columns)
X_test = pd.DataFrame(columns = X_columns)
y_train = pd.DataFrame(columns = y_columns)
y_test = pd.DataFrame(columns = y_columns)
# Below are the lists for KNN results

KNN_UtilityScore_mean = []
KNN_UtilityScore_std = []

KNN_F1Score_mean = []
KNN_F1Score_std = []

KNN_auroc_mean = []
KNN_auprc_mean = []

KNN_accuracy_mean = []
KNN_accuracy_std = []

KNN_positiveprediction_mean = []
KNN_baseline_mean = [ ]

KNN_total_Time= [ ]


fillmethod =""

Data size: (7593, 43)
Patient id size: 200

In [3]:
#This block will shuffle the id sets of patients in a fix manner, so for every time you run the code, the dataset and trainset are always the same.
seed = 2
random.seed(seed)
if(np.array_equal(Original_Uniq_ID,Uniq_ID) ):
    print("They are the same. Uniq id hasn't been shuffled, and it will be shuffeld now.")   
    random.shuffle(Uniq_ID)# randomly sorted the patient IDs    
else:
    print("They are not the same. Uniq_id has already been shuffled.")    
print("The original uniq id set is:\n",Original_Uniq_ID[1:20])
print("Uniq id:************************************")
print("The fixed shuffelld id set, it should be 211 275 153 189 184 110 124  49 345...\n",Uniq_ID[1:20])

They are the same. Uniq id hasn't been shuffled, and it will be shuffeld now.
The original uniq id set is:
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Uniq id:************************************
The fixed shuffelld id set, it should be 211 275 153 189 184 110 124  49 345...
 [ 95  56  36 171 178  21  86  51  37  31  77   6 137 183  83  26 170 167
 179]

In [4]:
def printDataset():
    print('X train shape:',X_train.shape)
    print(X_train)
    print( 'Y train shape:',y_train.shape)
    print(y_train)
    print('X test shape:',X_test.shape)
    print(X_test)
    print( 'Y test shape:',y_test.shape)
    print(y_test)
    
def clearAllDatasets():
    global X_train, X_test, y_train, y_test
    if not X_train.empty: 
        X_train = X_train[0:0]
    if not X_test.empty:
        X_test = X_test[0:0]
    if not y_train.empty:
        y_train = y_train[0:0]
    if not y_test.empty:
        y_test = y_test[0:0]
        
def KNN_reset():
    #KNN with different K size, 
    KNN_UtilityScore_mean.clear()
    KNN_UtilityScore_std.clear()
    KNN_F1Score_mean.clear()
    KNN_F1Score_std.clear()
    KNN_auroc_mean.clear()
    KNN_auprc_mean.clear()
    KNN_accuracy_mean.clear()
    KNN_accuracy_std.clear()
    KNN_positiveprediction_mean.clear()
    KNN_baseline_mean.clear()
    KNN_total_Time.clear()
    
def generateTrainDataSet(patienIds):
    global X_train, y_train
    for i in patienIds:
#     print('Patient_id',i,':\n',dataByPatient.get_group(i),'\n')
        X_train = X_train.append(dataByPatient.get_group(i).loc[:, X_columns])
        y_train = y_train.append(dataByPatient.get_group(i).loc[:, y_columns])
    return X_train, y_train
 
def generateTestDataSet(patienIds):
    global X_test, y_test
    for i in patienIds:
#     print('Patient_id',i,':\n',dataByPatient.get_group(i),'\n')
        X_test = X_test.append(dataByPatient.get_group(i).loc[:, X_columns])
        y_test = y_test.append(dataByPatient.get_group(i).loc[:, y_columns]) 
    return X_test, y_test

# def CalculateSOFAScore(X_train_impute, X_test_impute):
#     pass

In [5]:
# Code for K-fold algorithm, Before this step the missing data has been filled, 
def KFold_patient(model, KforKFold=10,KforKNN=5, fillmethod=""):
    start = time.time()# time indicator for how long the Kfold func takes
    global X_train, X_test, y_train, y_test
    print("K Fold of ",KforKFold ," folds with KNN =",KforKNN)
    
    # initialisation of the array for storing the different intermediate results
    accuracy_model = []
    F1Score_model = []
    baseline_model= []
    auroc_model = []
    auprc_model = []
    physio_accuracy_model = []
    f_measure_model = []
    utility_score_model = []
    mean_train = 0
    positivepredictions = []
    #The unique id sets have been created and shuffled in a fix manner in the third block, you can just use it here and no more any other manipulation
    idSets = np.array_split(Uniq_ID, KforKFold)# divide the ids into K groups
    #print("Patients number: ", len(Uniq_ID)) #print('idSets arrays',idSets)
    #This for loop is for Kfold, calculating the results for K times
    for i in range(KforKFold):
        start1 = time.time()
        clearAllDatasets()
#         X_train, X_test, y_train, y_test = flib.clearAllDatasets(X_train, X_test, y_train, y_test) #first clear all the datasets
        print("for the",i+1,"th iteration",idSets[i])   
        t1 = time.time()
        X_test,y_test = generateTestDataSet(idSets[i])
        print("Time for splitting id to test:", round(time.time()- t1,2))
        
        t2= time.time()
        for j in range(KforKFold):
            if j != i:
                 X_train, y_train = generateTrainDataSet(idSets[j])
        print("Time for splitting id to train:", round(time.time()- t2,2))

        #printDataset()
        #Now the train and test dataset is generated
        #we can begin to train the model wit the training set and evaaulate the performance with the test sett   
#         X_train = X_train.drop('time', 1) X_test = X_test.drop('time', 1)
        X_train=X_train.astype('float64')
        X_test=X_test.astype('float64')    
        YTest_copy = y_test  # variable of joining the filled data (X) and Y (Train_output) 
        patientID_ytest = y_test['Patient_id']
        y_train = y_train.drop('Patient_id', 1)
        y_test = y_test.drop('Patient_id', 1)      
        y_train=y_train.astype('float64')
        y_test=y_test.astype('float64')
        #print('YTest',YTest_copy.head())
        
        #fill the missing data
        if X_train.isnull().values.any() or X_test.isnull().values.any() :
            print("X_train or X_test contains NaN values, KNN/mean is performed.")
            #if there is missing value
            X_train_impute, X_test_impute, fillmethod = flib.KNNfilling(X_train, X_test, KforKNN, fillmethod)
            #X_train_impute, X_test_impute,fillmethod = flib.MeanFilling(X_train,X_test, fillmethod)
            #check the missing data   
            if np.isnan(X_train_impute).any() or np.isnan(X_test_impute).any() :
                print("X_train_impute or X_test_impute still contains NaN values")        
            else:
                print("X_train_impute or X_test_impute have all been filled ")  
        else:
            print("X_train or X_test have all been filled ")
            X_train_impute = X_train
            X_test_impute = X_test
                 
        #Scale the data， uncomment this part for logistic regression only, in other case, put them in comment
        model_name = type(model).__name__
        if (model_name == 'LogisticRegression'):
            print("scaled!")
            scaler = preprocessing.StandardScaler()
            scaler.fit(X_train_impute)
            X_train_impute = scaler.transform(X_train_impute)
            X_test_impute = scaler.transform(X_test_impute)

        #fit the model and predict
        model.fit(X_train_impute, y_train)
        y_predicted = model.predict(X_test_impute)   
        y_predicted_probobility = model.predict_proba(X_test_impute) 
        #transfer the outpu and evalute it
        y_labels = y_test.astype(int).to_numpy()
        y_predicted = y_predicted.astype(int)
        y_predicted_probobility =  y_predicted_probobility[:,1].round(4)
        #print(y_labels)      
        auroc, auprc, physio_accuracy, f_measure, utility_score = evaluate_performance(y_labels, y_predicted, y_predicted_probobility,patientID_ytest)
#         print("\nauroc",round(auroc,4),"auprc",round(auprc,4),"util_accuracy",round(accuracy1,4))
#         print("f_measure",round(f_measure,4),"utility_score",round(utility_score,4))  
        auroc_model.append(round(auroc,4))
        auprc_model.append(round(auprc,4))
        physio_accuracy_model.append(round(physio_accuracy,4))
        f_measure_model.append(round(f_measure,4))
        utility_score_model.append(round(utility_score,4))
        positivepredictions.append(np.sum(y_predicted))

        num_rows= X_test_impute.shape[0]
        scores = np.zeros(num_rows).astype('float64')# score parameter:output from get_sepsis_score
        labels = np.zeros(num_rows).astype('float64')
        #WriteToFiles(X_train_impute,YTest_copy,i, fillmethod)
        #CalcMean_Std(X_train_impute)
        #take down the results
        accuracy_model.append((accuracy_score(y_test, y_predicted, normalize=True)*100).round(2))
        F1Score_model.append((f1_score(y_test, y_predicted)*100).round(2))
        baseline_model.append(round( (1 - float(y_test.mean()) )*100 , 2 ))
        print("\ny_test size:",y_test.shape, '1´s in y_test',y_test.sum())
        #baseline_model.append(((1-y_test.mean())*100).round(2))
        print("The number of 1 (SepsisLabel) in this prediction: ", np.sum(y_predicted))
        end1 = time.time()
        print("Time spent in this KFold iteration",round(end1-start1,2),"sec.\n")
        print("******************************************************************")
    print('Accuracy model:', accuracy_model)
    print('F1_score model:', F1Score_model)
    print('Baseline model:', baseline_model)   
    print("\nEvaluation parameters of the utiltiy evaluation function:")
    print('auroc of model:', auroc_model)
    print('auprc of model:', auprc_model)
    print('Utility accuracy of model:', accuracy_model)
    print('utility F1 of model:', f_measure_model)
    print('Utility score of model:', utility_score_model)
    KNN_UtilityScore_mean.append(np.mean(utility_score_model))
    KNN_UtilityScore_std.append(np.std(utility_score_model))
    KNN_F1Score_mean.append(np.mean(f_measure_model))
    KNN_F1Score_std.append(np.std(f_measure_model))
    KNN_auroc_mean.append(np.mean(auroc_model))
    KNN_auprc_mean.append(np.mean(auprc_model))
    KNN_accuracy_mean.append(np.mean(physio_accuracy_model))
    KNN_accuracy_std.append(np.std(physio_accuracy_model))
    KNN_positiveprediction_mean.append(np.mean(positivepredictions))
    KNN_baseline_mean.append(np.mean(baseline_model))
    
    totalTime=round(time.time()- start,2)
    KNN_total_Time.append(totalTime)
    print("\nTotal Time spent in  KFold function",totalTime,"sec.\n")

In [6]:
def displayCurrentResult(KforKNNstart,KforKNNend):
    print("KNN_UtilityScore_mean",KNN_UtilityScore_mean)
    print("KNN_UtilityScore_std",KNN_UtilityScore_std)
    print("KNN_F1Score_mean",KNN_F1Score_mean)
    print("KNN_F1Score_std",KNN_F1Score_std)
    print("KNN_auroc_mean",KNN_auroc_mean)
    print("KNN_auprc_mean",KNN_auprc_mean)
    print("KNN_accuracy_mean",KNN_accuracy_mean)
    print("KNN_accuracy_std",KNN_accuracy_std)
    print("KNN_positiveprediction_mean",KNN_positiveprediction_mean)
    print("KNN_baseline_mean",KNN_baseline_mean)        
    print(len(KNN_accuracy_mean))
    print(len(KNN_accuracy_std))
    print(len(KNN_F1Score_mean))
    print(len(KNN_F1Score_std))
    print(len(KNN_positiveprediction_mean))
#     plotKNNResultFigure(KforKNNstart,KforKNNend,KNN_UtilityScore_mean,"Mean Utility Score vs K",xlabel='K',ylabel="mean Utility Score")
#     plotKNNResultFigure(KforKNNstart,KforKNNend,KNN_UtilityScore_std,"std Utility Score vs K",xlabel='K',ylabel="std Utility Score")
#     plotKNNResultFigure(KforKNNstart,KforKNNend,KNN_F1Score_mean,"Mean F1 score vs K",xlabel='K',ylabel="Mean F1 score")
#     plotKNNResultFigure(KforKNNstart,KforKNNend,KNN_F1Score_std,"Std F1 score vs K",xlabel='K',ylabel="Std F1 score")
#     plotKNNResultFigure(KforKNNstart,KforKNNend,KNN_accuracy_mean,"Mean Accuracy vs K",xlabel='K',ylabel="Mean Accuracy")      
def findBestKforKNN(model, KforKFold=10,KforKNNstart=1,KforKNNend=10, stepsize=5):
    if(KforKNNend<=1):
        print("K must be a interger larger than 1")
        return
    KNN_reset()
    step=stepsize
    for i in range(KforKNNstart,KforKNNend+1,step) : 
        print("KNN of K = ",i)    
        KFold_patient(model,10,i)
    print("Now all the training is finished.")

In [7]:
#Here is how to train the model
#logisticRegressionModel = LogisticRegression(C=0.1,random_state=2,solver='saga', max_iter=1000,penalty='l1')
logisticRegressionModel = LogisticRegression(C=0.1,random_state=2,solver='lbfgs', max_iter=1000)
decisionTreeModel = tree.DecisionTreeClassifier(random_state=2)
randomForestModel = RandomForestClassifier(random_state=2)
XGBoostModel = XGBClassifier(random_state=2)
#AdaBoostModel = AdaBoostClassifier(random_state=2)

In [8]:
#fill the missing data with one function
print(filename)
#print(originalData)
if (originalData.isnull().values.any()):
    print('Data isn´t all filled before K-Fold Func')
    data=originalData
#data,fillmethod = flib.linearFillingAll(originalData,1, True)#forwardfilling + fill other missing data with 0
dataByPatient = data.groupby('Patient_id') # data grouped by Patient_id
print("Maximum number of processes： ", mp.cpu_count())

raw_data/raw_data_200.csv
Data isn´t all filled before K-Fold Func
Maximum number of processes：  36

In [9]:
#Function for 1 fold in Kfold
def OneFold_patient_MP(i,model,KforKFold,KforKNN,idSets,fillmethod):
#def OneFold_patient_MP(i):
    start1 = time.time()
    clearAllDatasets()
#     X_train, X_test, y_train, y_test = flib.clearAllDatasets(X_train, X_test, y_train, y_test) #first clear all the datasets
    print("for the",i+1,"th iteration",idSets[i])   
    t1 = time.time()
    X_test,y_test = generateTestDataSet(idSets[i])
    print("Time for splitting id to test:", round(time.time()- t1,2))
    t2= time.time()
    for j in range(KforKFold):
        if j != i:
             X_train, y_train = generateTrainDataSet(idSets[j])
    print("Time for splitting id to train:", round(time.time()- t2,2))
    flib.printDataset(X_train, X_test, y_train, y_test)
    #Now the train and test dataset is generated
    #we can begin to train the model wit the training set and evaaulate the performance with the test sett   
#         X_train = X_train.drop('time', 1) X_test = X_test.drop('time', 1)
    X_train=X_train.astype('float64')
    X_test=X_test.astype('float64')    
    #YTest_copy = y_test  # variable of joining the filled data (X) and Y (Train_output) 
    patientID_ytest = y_test['Patient_id']
    y_train = y_train.drop('Patient_id', 1)
    y_test = y_test.drop('Patient_id', 1)      
    y_train=y_train.astype('float64')
    y_test=y_test.astype('float64')
    #print('YTest',YTest_copy.head())

    #fill the missing data
    if X_train.isnull().values.any() or X_test.isnull().values.any() :
        print("X_train or X_test contains NaN values, KNN/mean is performed.")
        #if there is missing value
        X_train_impute, X_test_impute, fillmethod = flib.KNNfilling(X_train, X_test, KforKNN, fillmethod)
        #X_train_impute, X_test_impute,fillmethod = flib.MeanFilling(X_train,X_test, fillmethod)
        #check the missing data   
        if np.isnan(X_train_impute).any() or np.isnan(X_test_impute).any() :
            print("X_train_impute or X_test_impute still contains NaN values")        
        else:
            print("X_train_impute or X_test_impute have all been filled ")  
    else:
        print("X_train or X_test have all been filled ")
        X_train_impute = X_train
        X_test_impute = X_test

    #Scale the data， uncomment this part for logistic regression only, in other case, put them in comment
#     model_name = type(model).__name__
#     if (model_name == 'LogisticRegression'):
#         print("scaled!")
#         scaler = preprocessing.StandardScaler()
#         scaler.fit(X_train_impute)
#         X_train_impute = scaler.transform(X_train_impute)
#         X_test_impute = scaler.transform(X_test_impute)

    #fit the model and predict
    model.fit(X_train_impute, y_train)
    y_predicted = model.predict(X_test_impute)   
    y_predicted_probobility = model.predict_proba(X_test_impute) 
    #transfer the outpu and evalute it
    y_labels = y_test.astype(int).to_numpy()
    y_predicted = y_predicted.astype(int)
    y_predicted_probobility =  y_predicted_probobility[:,1].round(4)
    #print(y_labels)      
    auroc, auprc, physio_accuracy, f_measure, utility_score = evaluate_performance(y_labels, y_predicted, y_predicted_probobility,patientID_ytest)
#         print("\nauroc",round(auroc,4),"auprc",round(auprc,4),"util_accuracy",round(accuracy1,4))
#         print("f_measure",round(f_measure,4),"utility_score",round(utility_score,4))  
    result = { "auroc": round(auroc,4), "auprc": round(auprc,4), "f_measure": round(f_measure,4),
        "physio_accuracy": round(physio_accuracy,4),"utility_score": round(utility_score,4), 
        "positiveprediction": np.sum(y_predicted), "accuracy": (accuracy_score(y_test, y_predicted, normalize=True)*100).round(2), 
        "F1Score": (f1_score(y_test, y_predicted)*100).round(2),
        "baseline": round( (1 - float(y_test.mean()) )*100 , 2 )
}
#     auroc_model.append(round(auroc,4))
#     auprc_model.append(round(auprc,4))
#     physio_accuracy_model.append(round(physio_accuracy,4))
#     f_measure_model.append(round(f_measure,4))
#     utility_score_model.append(round(utility_score,4))
#     positivepredictions.append(np.sum(y_predicted))
#     num_rows= X_test_impute.shape[0]
#     scores = np.zeros(num_rows).astype('float64')# score parameter:output from get_sepsis_score
#     labels = np.zeros(num_rows).astype('float64')
    #WriteToFiles(X_train_impute,YTest_copy,i, fillmethod)
    #CalcMean_Std(X_train_impute)
    #take down the results

    
    print("\ny_test size:",y_test.shape, '1´s in y_test',y_test.sum())
    
    end1 = time.time()
    print("Time spent in ",i,"th Fold iteration",round(end1-start1,2),"sec.\n")
    print("******************************************************************")
    return result

In [10]:
# Code for K-fold algorithm using multi processes
def KFold_patient_MP(model, KforKFold=10,KforKNN=5, fillmethod=""):
    start = time.time()# time indicator for how long the Kfold func takes
    global X_train, X_test, y_train, y_test
    print("K Fold of ",KforKFold ," folds with KNN =",KforKNN)
    # initialisation of the array for storing the different intermediate results
    
    auroc_model = []
    auprc_model = []
    f_measure_model = []
    physio_accuracy_model = []
    utility_score_model = []
    positivepredictions = []
    accuracy_model = []
    F1Score_model = []
    baseline_model= []
    
    mean_train = 0
    #The unique id sets have been created and shuffled in a fix manner in the third block, you can just use it here and no more any other manipulation
    idSets = np.array_split(Uniq_ID, KforKFold)# divide the ids into K groups
    #print("Patients number: ", len(Uniq_ID)) #print('idSets arrays',idSets)
    #This for loop is for Kfold using multi processes
    
    folds = list(range(0,KforKFold))
    
#     with ProcessPoolExecutor (max_workers = 10) as executor:  
#         results = executor.submit(OneFold_patient_MP, folds)
        
#         for result in results:
#             print(result)

    pool = mp.Pool(10)
    results = pool.starmap(OneFold_patient_MP, [(fold, model, KforKFold, KforKNN,idSets,fillmethod) for fold in folds])
    pool.close()
    pool.join()
    for result in results:
        auroc_model.append(result["auroc"])
        auprc_model.append(result["auprc"])
        f_measure_model.append(result["f_measure"])
        physio_accuracy_model.append(result["physio_accuracy"])  
        utility_score_model.append(result["utility_score"])
        positivepredictions.append(result["positiveprediction"])
        accuracy_model.append(result["accuracy"])
        F1Score_model.append(result["F1Score"])
        baseline_model.append(result["baseline"])  
    print("\nEvaluation parameters of the utiltiy evaluation function:")
    print('auroc of model:', auroc_model)
    print('auprc of model:', auprc_model)
    print('utility F1 of model:', f_measure_model)
    print('Utility accuracy of model:', accuracy_model) 
    print('Utility score of model:', utility_score_model)
    print("Positive Prediction: ", positivepredictions)
    print('Accuracy model:', accuracy_model)
    print('F1_score model:', F1Score_model)
    print('Baseline model:', baseline_model)  
    KNN_auroc_mean.append(np.mean(auroc_model))
    KNN_auprc_mean.append(np.mean(auprc_model))
    KNN_F1Score_mean.append(np.mean(f_measure_model))
    KNN_F1Score_std.append(np.std(f_measure_model))
    KNN_accuracy_mean.append(np.mean(physio_accuracy_model))
    KNN_accuracy_std.append(np.std(physio_accuracy_model))
    KNN_UtilityScore_mean.append(np.mean(utility_score_model))
    KNN_UtilityScore_std.append(np.std(utility_score_model))
    KNN_positiveprediction_mean.append(np.mean(positivepredictions))
    KNN_baseline_mean.append(np.mean(baseline_model))
    
    totalTime=round(time.time()- start,2)
    KNN_total_Time.append(totalTime)
    print("\nTotal Time spent in  KFold function",totalTime,"sec.\n")

In [11]:
KFold_patient_MP(decisionTreeModel,10, 1)

K Fold of  10  folds with KNN = 1
for thefor thefor thefor the for thefor the for thefor the  1 2 3  6 7 8 9 10th iteration th iteration th iteration th iteration   th iterationth iteration th iteration th iteration   [ 75  54  33 185 161 180 139 141  28  13  49  58 146  29  20 163 176 122
  19  73] [ 52  95  56  36 171 178  21  86  51  37  31  77   6 137 183  83  26 170
 167 179][102  70  50 116 182  16 194  38 112   1 159  34  12  48  81 127 184  17
 199  92][148 145  53  76 187 160 110  67 138 192 123 134 143  39  40  62  99 158
 193 130]
[113 198 150 195 105 153 121  57 125 133  90 142 117 147 154 177 128  72
 126  64][136 119 103  42 151 155  91 173 168 107 115  47 166 132 197 157 181  35
  45  84][165   7  60  61  46 144  43 135 109  98  82 120  94   8 188  69 129 114
 140  96]


[131 101 164 111  41 175 149  10 191  55 156  65  79 172 189  44  93  22
  24  15]



Time for splitting id to test: 0.1
Time for splitting id to test: 0.11Time for splitting id to test:
0.11
Time for splitting id to test:Time for splitting id to test:Time for splitting id to test:   Time for splitting id to test:0.110.110.11Time for splitting id to test:


0.170.17

for thefor the  45  th iterationth iteration  [ 59  71   3  68   9 200  11   4  78  23 169  97  87   5 190  89 100  32
  85  18][108 124  30 104 118 162 106  74 174  14  25   2 196 186  80  88 152  66
  63  27]

Time for splitting id to test: 0.2
Time for splitting id to test: 0.2
Time for splitting id to train: 2.16
X train shape: (7005, 42)
        HR  O2Sat   Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
2681   NaN    NaN    NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
2682  70.0   99.0  36.11  107.0  76.00   NaN  14.0    NaN         2.0   NaN
2683  74.0   99.0    NaN  111.0  74.00   NaN  14.0    NaN         NaN  23.0
2684  75.0   99.0  36.56  114.0  73.00   NaN  14.0    NaN         NaN   NaN
2685  84.0   98.0    NaN  132.0  92.00   NaN  14.0    NaN         NaN   NaN
...    ...    ...    ...    ...    ...   ...   ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.0    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0   NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.0    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.0    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2681  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
2682  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
2683  ...         NaN      243.0  34.34       0    1.0    0.0        -0.01
2684  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
2685  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2681       1          75     0
2682       2          75     1
2683       3          75     2
2684       4          75     3
2685       5          75     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[7005 rows x 42 columns]
Y train shape: (7005, 2)
     Patient_id SepsisLabel
2681         75           0
2682         75           0
2683         75           0
2684         75           0
2685         75           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[7005 rows x 2 columns]
X test shape: (588, 42)
        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5   81.0  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0   79.5  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0   72.5  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0   77.5  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0   72.0  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
6818  71.0   98.0  36.40  119.0   94.0  79.0  20.00    NaN         NaN   NaN
6819  75.0   98.0    NaN  130.0   99.0  79.0  19.00    NaN         NaN   NaN
6820  77.0   98.0    NaN  126.0   97.0  80.0  17.00    NaN         NaN   NaN
6821  74.0   99.0    NaN  122.0  100.0  84.0  20.00    NaN         NaN   NaN
6822  68.0   96.0  36.00  127.0  100.5  82.5  24.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
6818  ...         NaN        NaN  51.00       1    NaN    NaN      -281.40
6819  ...         NaN        NaN  51.00       1    NaN    NaN      -281.40
6820  ...         NaN        NaN  51.00       1    NaN    NaN      -281.40
6821  ...         NaN        NaN  51.00       1    NaN    NaN      -281.40
6822  ...         NaN        NaN  51.00       1    NaN    NaN      -281.40

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
6818      18         179    17
6819      19         179    18
6820      20         179    19
6821      21         179    20
6822      22         179    21

[588 rows x 42 columns]
Y test shape: (588, 2)
     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
6818        179           0
6819        179           0
6820        179           0
6821        179           0
6822        179           0

[588 rows x 2 columns]
X_train or X_test contains NaN values, KNN/mean is performed.
Time for splitting id to train: 2.31
X train shape: (6849, 42)
Time for splitting id to train: 2.33        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6849 rows x 42 columns]

X train shape:Y train shape:  (6854, 42)(6849, 2)

     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6849 rows x 2 columns]
X test shape: (744, 42)
        HR  O2Sat   Temp    SBP   MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.0  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.5  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.5  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.5  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.0  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...   ...   ...    ...    ...         ...   ...
3551  53.0   97.0    NaN  137.0  90.0  71.0  24.00    NaN         NaN   NaN
3552  52.0   96.0  36.61  139.0  91.0  72.0  24.00    NaN         NaN   NaN
3553  55.0   94.0    NaN  127.0  79.0  60.0  23.00    NaN         NaN   NaN
3554  54.0   95.0    NaN  115.0  80.0   NaN  26.00    NaN         NaN   NaN
3555   NaN    NaN    NaN    NaN   NaN   NaN    NaN    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
3551  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3552  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3553  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3554  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3555  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
3551      15          96    14
3552      16          96    15
3553      17          96    16
3554      18          96    17
3555      19          96    18

[6854 rows x 42 columns]
Y train shape:          HR  O2Sat   Temp    SBP     MAP  DBP  Resp  EtCO2  BaseExcess  HCO3  \
2681    NaN    NaN    NaN    NaN     NaN  NaN   NaN    NaN         NaN   NaN
2682   70.0   99.0  36.11  107.0   76.00  NaN  14.0    NaN         2.0   NaN
2683   74.0   99.0    NaN  111.0   74.00  NaN  14.0    NaN         NaN  23.0
2684   75.0   99.0  36.56  114.0   73.00  NaN  14.0    NaN         NaN   NaN
2685   84.0   98.0    NaN  132.0   92.00  NaN  14.0    NaN         NaN   NaN
...     ...    ...    ...    ...     ...  ...   ...    ...         ...   ...
2663   91.0    NaN    NaN    NaN     NaN  NaN  22.0    NaN         NaN   NaN
2664   95.0    NaN  37.00    NaN     NaN  NaN  21.0    NaN         NaN   NaN
2665   87.0   96.0    NaN  123.0   90.33  NaN  20.0    NaN         NaN   NaN
2666  104.0    NaN    NaN    NaN     NaN  NaN  22.0    NaN         NaN   NaN
2667  100.0    NaN    NaN  138.0  104.67  NaN  24.0    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2681  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
2682  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
2683  ...         NaN      243.0  34.34       0    1.0    0.0        -0.01
2684  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
2685  ...         NaN        NaN  34.34       0    1.0    0.0        -0.01
...   ...         ...        ...    ...     ...    ...    ...          ...
2663  ...         NaN        NaN  42.60       1    NaN    NaN        -2.31
2664  ...         NaN        NaN  42.60       1    NaN    NaN        -2.31
2665  ...         NaN        NaN  42.60       1    NaN    NaN        -2.31
2666  ...         NaN        NaN  42.60       1    NaN    NaN        -2.31
2667  ...         NaN        NaN  42.60       1    NaN    NaN        -2.31

      ICULOS  Patient_id  time
2681       1          75     0
2682       2          75     1
2683       3          75     2
2684       4          75     3
2685       5          75     4
...      ...         ...   ...
2663      19          73    18
2664      20          73    19
2665      21          73    20
2666      22          73    21
2667      23          73    22

[744 rows x 42 columns](6854, 2)

Y test shape: (744, 2)
     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
3551         96           0
3552         96           0
3553         96           0
3554         96           0
3555         96           0

[6854 rows x 2 columns]
X test shape:Time for splitting id to train:      Patient_id SepsisLabel
2681         75           0
2682         75           0
2683         75           0
2684         75           0
2685         75           0
...         ...         ...
2663         73           0
2664         73           0
2665         73           0
2666         73           0
2667         73           0

[744 rows x 2 columns] (739, 42)
2.42

X train shape: (6933, 42)
Time for splitting id to train:Time for splitting id to train: X_train or X_test contains NaN values, KNN/mean is performed. 2.5
2.5

X train shape:X train shape:  (6697, 42)(6906, 42)

        HR  O2Sat  Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
5101   NaN    NaN   NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
5102  83.0   97.0  36.8  146.0  96.00  67.0  13.0    NaN         NaN   NaN
5103  86.5   96.5  36.3  154.5  98.00  68.5  17.0    NaN         NaN   NaN
5104  88.0   97.0   NaN  133.0  87.00  60.0  21.0    NaN         NaN   NaN
5105  89.0   97.0   NaN  165.0  97.00  67.0  12.0    NaN         NaN   NaN
...    ...    ...   ...    ...    ...   ...   ...    ...         ...   ...
731    NaN    NaN   NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
732   89.0    NaN  36.9  130.0  97.00  77.0  12.0    NaN         NaN   NaN
733   87.0    NaN  36.9  124.0  93.33  76.0   NaN    NaN         NaN   NaN
734   82.0    NaN  36.7  113.0  86.00  69.0  12.0    NaN         NaN   NaN
735   87.5    NaN  36.7  103.5  80.50  66.0  13.0    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
5101  ...         NaN        NaN  65.00       0    NaN    NaN      -106.77
5102  ...         NaN        NaN  65.00       0    NaN    NaN      -106.77
5103  ...         NaN        NaN  65.00       0    NaN    NaN      -106.77
5104  ...         NaN        NaN  65.00       0    NaN    NaN      -106.77
5105  ...         NaN        NaN  65.00       0    NaN    NaN      -106.77
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
5101       1         131     0
5102       2         131     1
5103       3         131     2
5104       4         131     3
5105       5         131     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[739 rows x 42 columns]
Y test shape: (739, 2)
     Patient_id SepsisLabel
5101        131           0
5102        131           0
5103        131           0
5104        131           0
5105        131           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[739 rows x 2 columns]
        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6697 rows x 42 columns]Time for splitting id to train: 2.59
        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6906 rows x 42 columns]
Y train shape: X_train or X_test contains NaN values, KNN/mean is performed.
X train shape:(6906, 2)Y train shape: Time for splitting id to train:(6901, 42)
         HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6933 rows x 42 columns] 2.52

(6697, 2)        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6901 rows x 42 columns]


Y train shape:X train shape:     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6906 rows x 2 columns]      Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6697 rows x 2 columns]

(6933, 2)Y train shape:X test shape:

       Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6933 rows x 2 columns](687, 42) X test shape:(6901, 2)

     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6901 rows x 2 columns](896, 42)
(6822, 42)

X test shape:
X test shape:  (692, 42)(660, 42)

        HR  O2Sat   Temp    SBP   MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
3728   NaN    NaN    NaN    NaN   NaN   NaN   NaN    NaN         NaN   NaN
3729  56.5  100.0  35.20  129.0  75.0  52.5  23.0   35.0         NaN   NaN
3730  61.0  100.0  35.80   86.0  56.0  43.0  17.0   39.0         NaN   NaN
3731  64.5   99.0  36.90  103.0  59.0  41.0  20.0   37.5         NaN   NaN
3732  71.5   97.0  37.20  136.5  81.5  52.5  22.5    NaN         NaN   NaN
...    ...    ...    ...    ...   ...   ...   ...    ...         ...   ...
3431  67.0  100.0    NaN  106.0  63.0   NaN  14.0    NaN         NaN   NaN
3432  67.0   95.0    NaN  114.0  64.0   NaN  14.0    NaN         NaN   NaN
3433  64.0   95.0  35.28    NaN   NaN   NaN  15.0    NaN         NaN   NaN
3434  63.0   98.0    NaN  126.0  74.0   NaN  13.0    NaN         NaN   NaN
3435  69.0   97.0    NaN  137.0  78.0   NaN  20.0    NaN         NaN   NaN

      ...  Fibrinogen  Platelets   Age  Gender  Unit1  Unit2  HospAdmTime  \
3728  ...         NaN        NaN  83.0       1    0.0    1.0      -123.17
3729  ...         NaN        NaN  83.0       1    0.0    1.0      -123.17
3730  ...         NaN        NaN  83.0       1    0.0    1.0      -123.17
3731  ...         NaN        NaN  83.0       1    0.0    1.0      -123.17
3732  ...         NaN        NaN  83.0       1    0.0    1.0      -123.17
...   ...         ...        ...   ...     ...    ...    ...          ...
3431  ...         NaN        NaN  71.1       1    1.0    0.0        -0.92
3432  ...         NaN        NaN  71.1       1    1.0    0.0        -0.92
3433  ...         NaN        NaN  71.1       1    1.0    0.0        -0.92
3434  ...         NaN        NaN  71.1       1    1.0    0.0        -0.92
3435  ...         NaN        NaN  71.1       1    1.0    0.0        -0.92

      ICULOS  Patient_id  time
3728       1         102     0
3729       2         102     1
3730       3         102     2
3731       4         102     3
3732       5         102     4
...      ...         ...   ...
3431      28          92    27
3432      29          92    28
3433      30          92    29
3434      31          92    30
3435      32          92    31

[896 rows x 42 columns]        HR  O2Sat   Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
6343   NaN    NaN    NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
6344  71.0  100.0    NaN  130.5   87.0  72.5  16.0    NaN         NaN   NaN
6345  75.5  100.0  37.90  139.0  102.5  83.0  14.0    NaN         NaN   NaN
6346  67.0  100.0    NaN  197.0  117.0  81.0  17.0    NaN         NaN   NaN
6347  68.5  100.0    NaN  152.0   99.5  71.0  15.5    NaN         NaN   NaN
...    ...    ...    ...    ...    ...   ...   ...    ...         ...   ...
3551  53.0   97.0    NaN  137.0   90.0  71.0  24.0    NaN         NaN   NaN
3552  52.0   96.0  36.61  139.0   91.0  72.0  24.0    NaN         NaN   NaN
3553  55.0   94.0    NaN  127.0   79.0  60.0  23.0    NaN         NaN   NaN
3554  54.0   95.0    NaN  115.0   80.0   NaN  26.0    NaN         NaN   NaN
3555   NaN    NaN    NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
6343  ...         NaN        NaN  61.00       1    NaN    NaN      -479.12
6344  ...         NaN        NaN  61.00       1    NaN    NaN      -479.12
6345  ...         NaN      277.0  61.00       1    NaN    NaN      -479.12
6346  ...         NaN        NaN  61.00       1    NaN    NaN      -479.12
6347  ...         NaN        NaN  61.00       1    NaN    NaN      -479.12
...   ...         ...        ...    ...     ...    ...    ...          ...
3551  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3552  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3553  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3554  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03
3555  ...         NaN        NaN  56.09       1    NaN    NaN        -0.03

      ICULOS  Patient_id  time
6343       1         165     0
6344       2         165     1
6345       3         165     2
6346       4         165     3
6347       5         165     4
...      ...         ...   ...
3551      15          96    14
3552      16          96    15
3553      17          96    16
3554      18          96    17
3555      19          96    18

[687 rows x 42 columns]         HR  O2Sat  Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
5684    NaN    NaN   NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
5685  156.5   96.0   NaN  114.5   86.5  78.0  29.0    NaN         NaN   NaN
5686  126.0   96.0   NaN  116.0   87.0  76.0   NaN    NaN         NaN   NaN
5687  113.0   96.5   NaN  118.0   79.5  68.5  29.5    NaN         NaN   NaN
5688  112.0   95.0   NaN   99.0  103.0  57.0  28.0    NaN         NaN   NaN
...     ...    ...   ...    ...    ...   ...   ...    ...         ...   ...
5096  100.0  100.0   NaN  121.0   67.5  50.5   NaN   42.0         NaN   NaN
5097   97.0  100.0   NaN  131.0   69.0  51.0   2.0   35.0         NaN   NaN
5098   98.0  100.0   NaN  134.0   70.0  49.0   1.0   37.0         NaN   NaN
5099   97.0  100.0   NaN  141.0   74.0  51.0   4.0   36.5         NaN   NaN
5100  101.0  100.0   NaN  133.0   69.0  46.0   1.0   38.0         NaN   NaN

      ...  Fibrinogen  Platelets   Age  Gender  Unit1  Unit2  HospAdmTime  \
5684  ...         NaN        NaN  65.0       0    1.0    0.0       -70.48
5685  ...         NaN        NaN  65.0       0    1.0    0.0       -70.48
5686  ...         NaN        NaN  65.0       0    1.0    0.0       -70.48
5687  ...         NaN        NaN  65.0       0    1.0    0.0       -70.48
5688  ...         NaN        NaN  65.0       0    1.0    0.0       -70.48
...   ...         ...        ...   ...     ...    ...    ...          ...
5096  ...         NaN        NaN  46.0       1    1.0    0.0       -44.60
5097  ...         NaN        NaN  46.0       1    1.0    0.0       -44.60
5098  ...         NaN        NaN  46.0       1    1.0    0.0       -44.60
5099  ...         NaN        NaN  46.0       1    1.0    0.0       -44.60
5100  ...         NaN        NaN  46.0       1    1.0    0.0       -44.60

      ICULOS  Patient_id  time
5684       1         148     0
5685       2         148     1
5686       3         148     2
5687       4         148     3
5688       5         148     4
...      ...         ...   ...
5096      46         130    45
5097      47         130    46
5098      48         130    47
5099      49         130    48
5100      50         130    49

[660 rows x 42 columns]
        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6822 rows x 42 columns]        HR  O2Sat   Temp    SBP   MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
4180   NaN    NaN    NaN    NaN   NaN   NaN   NaN    NaN         NaN   NaN
4181  84.0   98.0    NaN    NaN   NaN   NaN   NaN    NaN         NaN   NaN
4182  90.0   97.0  35.80  108.0  80.0  65.0  24.0    NaN         NaN   NaN
4183  93.0   98.0    NaN   89.0  73.0  66.0  25.0    NaN         NaN   NaN
4184   NaN    NaN    NaN    NaN   NaN   NaN   NaN    NaN         NaN   NaN
...    ...    ...    ...    ...   ...   ...   ...    ...         ...   ...
2406  91.0  100.0    NaN  108.0  67.0  47.0  15.0    NaN         NaN   NaN
2407  94.0  100.0  37.33  110.0  68.0  47.0  18.5    NaN         NaN   NaN
2408  83.0  100.0    NaN  128.0  83.0  57.0  20.0    NaN         NaN   NaN
2409  84.0  100.0    NaN  119.0  75.0  53.0  21.0    NaN         NaN   NaN
2410  86.0  100.0    NaN  116.0  74.0  52.0  21.0    NaN         NaN  14.0

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
4180  ...         NaN        NaN  89.00       1    1.0    0.0      -253.56
4181  ...         NaN        NaN  89.00       1    1.0    0.0      -253.56
4182  ...         NaN        NaN  89.00       1    1.0    0.0      -253.56
4183  ...         NaN        NaN  89.00       1    1.0    0.0      -253.56
4184  ...         NaN        NaN  89.00       1    1.0    0.0      -253.56
...   ...         ...        ...    ...     ...    ...    ...          ...
2406  ...         NaN        NaN  68.98       0    NaN    NaN        -0.01
2407  ...         NaN        NaN  68.98       0    NaN    NaN        -0.01
2408  ...         NaN        NaN  68.98       0    NaN    NaN        -0.01
2409  ...         NaN        NaN  68.98       0    NaN    NaN        -0.01
2410  ...         NaN      136.0  68.98       0    NaN    NaN        -0.01

      ICULOS  Patient_id  time
4180       1         113     0
4181       2         113     1
4182       3         113     2
4183       4         113     3
4184       5         113     4
...      ...         ...   ...
2406      25          64    23
2407      26          64    24
2408      27          64    25
2409      28          64    26
2410      29          64    27

[692 rows x 42 columns]Y test shape:

 Y train shape:(687, 2)
Y test shape:      Patient_id SepsisLabel
6343        165           0
6344        165           0
6345        165           0
6346        165           0
6347        165           0
...         ...         ...
3551         96           0
3552         96           0
3553         96           0
3554         96           0
3555         96           0

[687 rows x 2 columns](692, 2)
Y test shape:


Y test shape:      Patient_id SepsisLabel
4180        113           0
4181        113           0
4182        113           0
4183        113           0
4184        113           0
...         ...         ...
2406         64           1
2407         64           1
2408         64           1
2409         64           1
2410         64           1

[692 rows x 2 columns](660, 2)(6822, 2)
X_train or X_test contains NaN values, KNN/mean is performed.
      Patient_id SepsisLabel
5684        148           0
5685        148           0
5686        148           0
5687        148           0
5688        148           0
...         ...         ...
5096        130           0
5097        130           0
5098        130           0
5099        130           0
5100        130           0

[660 rows x 2 columns](896, 2)



     Patient_id SepsisLabel
3728        102           0
3729        102           0
3730        102           0
3731        102           0
3732        102           0
...         ...         ...
3431         92           0
3432         92           0
3433         92           0
3434         92           0
3435         92           0

[896 rows x 2 columns]X_train or X_test contains NaN values, KNN/mean is performed.     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6822 rows x 2 columns]
X_train or X_test contains NaN values, KNN/mean is performed.


X test shape: (771, 42)
X_train or X_test contains NaN values, KNN/mean is performed.
         HR  O2Sat   Temp    SBP   MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
5260    NaN    NaN    NaN    NaN   NaN   NaN   NaN    NaN         NaN   NaN
5261   90.0   99.0  36.80  152.0  92.0  74.0  16.0    NaN         NaN   NaN
5262   85.0   99.0    NaN  130.5  77.0  57.0  16.0    NaN         NaN   NaN
5263   85.0   99.0    NaN  138.0  80.0  60.0  17.0    NaN         NaN   NaN
5264   82.0   99.5  37.10  123.5  77.5  62.0  15.0    NaN         NaN   NaN
...     ...    ...    ...    ...   ...   ...   ...    ...         ...   ...
3142   93.0  100.0  38.22  114.0  74.0   NaN  14.0    NaN         NaN  24.0
3143  100.0   99.0    NaN  127.0  85.0   NaN  24.0    NaN         NaN   NaN
3144   97.0   98.0    NaN  132.0  92.0   NaN  25.0    NaN         NaN   NaN
3145  102.0   98.0  37.17  113.0  69.0   NaN  21.0    NaN         NaN   NaN
3146  106.0   99.0    NaN  108.0  78.0   NaN  22.0    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
5260  ...         NaN        NaN  66.00       0    NaN    NaN        -3.43
5261  ...         NaN        NaN  66.00       0    NaN    NaN        -3.43
5262  ...         NaN        NaN  66.00       0    NaN    NaN        -3.43
5263  ...         NaN        NaN  66.00       0    NaN    NaN        -3.43
5264  ...         NaN        NaN  66.00       0    NaN    NaN        -3.43
...   ...         ...        ...    ...     ...    ...    ...          ...
3142  ...         NaN      135.0  62.52       1    1.0    0.0        -0.07
3143  ...         NaN        NaN  62.52       1    1.0    0.0        -0.07
3144  ...         NaN        NaN  62.52       1    1.0    0.0        -0.07
3145  ...         NaN        NaN  62.52       1    1.0    0.0        -0.07
3146  ...         NaN        NaN  62.52       1    1.0    0.0        -0.07

      ICULOS  Patient_id  time
5260       1         136     0
5261       2         136     1
5262       3         136     2
5263       4         136     3
5264       5         136     4
...      ...         ...   ...
3142      38          84    37
3143      39          84    38
3144      40          84    39
3145      41          84    40
3146      42          84    41

[771 rows x 42 columns]
Y test shape: (771, 2)
     Patient_id SepsisLabel
5260        136           0
5261        136           0
5262        136           0
5263        136           0
5264        136           0
...         ...         ...
3142         84           0
3143         84           0
3144         84           0
3145         84           0
3146         84           0

[771 rows x 2 columns]
X_train or X_test contains NaN values, KNN/mean is performed.
Time for splitting id to train:Time for splitting id to train:  4.01
X train shape: (6959, 42)
3.99
X train shape:        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6959 rows x 42 columns]
 (6411, 42)Y train shape:
 (6959, 2)
     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6959 rows x 2 columns]
        HR  O2Sat   Temp    SBP    MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
2073  84.0  100.0  34.90  111.5  81.00  63.5  12.25    NaN         NaN  24.0
2074  87.5  100.0  34.75  107.0  79.50  63.5  12.00    NaN         0.0   NaN
2075  90.0  100.0  35.25   96.0  72.50  59.5  12.00    NaN         0.0   NaN
2076  90.0  100.0  35.85  107.0  77.50  61.0  12.00    NaN         NaN   NaN
2077  82.0  100.0  36.30   99.0  72.00  57.0  12.00    NaN        -2.0   NaN
...    ...    ...    ...    ...    ...   ...    ...    ...         ...   ...
731    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN         NaN   NaN
732   89.0    NaN  36.90  130.0  97.00  77.0  12.00    NaN         NaN   NaN
733   87.0    NaN  36.90  124.0  93.33  76.0    NaN    NaN         NaN   NaN
734   82.0    NaN  36.70  113.0  86.00  69.0  12.00    NaN         NaN   NaN
735   87.5    NaN  36.70  103.5  80.50  66.0  13.00    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2073  ...         NaN      212.0  61.34       1    0.0    1.0       -62.99
2074  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2075  ...         NaN      225.0  61.34       1    0.0    1.0       -62.99
2076  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
2077  ...         NaN        NaN  61.34       1    0.0    1.0       -62.99
...   ...         ...        ...    ...     ...    ...    ...          ...
731   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
732   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
733   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
734   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34
735   ...         NaN        NaN  58.54       0    NaN    NaN      -405.34

      ICULOS  Patient_id  time
2073       2          52     0
2074       3          52     1
2075       4          52     2
2076       5          52     3
2077       6          52     4
...      ...         ...   ...
731       11          15    10
732       12          15    11
733       13          15    12
734       14          15    13
735       15          15    14

[6411 rows x 42 columns]X test shape:
 (634, 42)Y train shape:
(6411, 2)
     Patient_id SepsisLabel
2073         52           0
2074         52           0
2075         52           0
2076         52           0
2077         52           0
...         ...         ...
731          15           1
732          15           1
733          15           1
734          15           1
735          15           1

[6411 rows x 2 columns]
X test shape:         HR  O2Sat   Temp    SBP     MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
3991   NaN    NaN    NaN    NaN     NaN   NaN   NaN    NaN         NaN   NaN
3992  80.0   95.5  36.20  125.0   74.00  57.0  16.0   34.5         NaN   NaN
3993  85.0   99.0  36.10  137.0   79.00  61.0  16.0   36.0         NaN   NaN
3994  91.0   97.0  36.05  105.5   66.50  53.5  19.5   40.5         NaN   NaN
3995  94.5   98.0  36.05   91.0   63.50  53.5  23.0   42.5         NaN   NaN
...    ...    ...    ...    ...     ...   ...   ...    ...         ...   ...
1209  84.0   96.0  37.72  143.0   79.00   NaN  25.0    NaN         NaN   NaN
1210   NaN    NaN    NaN    NaN     NaN   NaN   NaN    NaN         NaN   NaN
1211  78.0   97.0    NaN  148.0  100.00   NaN  16.0    NaN         NaN   NaN
1212   NaN    NaN    NaN    NaN     NaN   NaN   NaN    NaN         NaN   NaN
1213  66.0  100.0  37.67  123.0   75.67   NaN  26.0    NaN         NaN   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
3991  ...         NaN        NaN  65.00       1    0.0    1.0      -211.64
3992  ...         NaN        NaN  65.00       1    0.0    1.0      -211.64
3993  ...         NaN        NaN  65.00       1    0.0    1.0      -211.64
3994  ...         NaN      134.0  65.00       1    0.0    1.0      -211.64
3995  ...         NaN        NaN  65.00       1    0.0    1.0      -211.64
...   ...         ...        ...    ...     ...    ...    ...          ...
1209  ...         NaN        NaN  47.95       0    0.0    1.0         0.00
1210  ...         NaN        NaN  47.95       0    0.0    1.0         0.00
1211  ...         NaN        NaN  47.95       0    0.0    1.0         0.00
1212  ...         NaN        NaN  47.95       0    0.0    1.0         0.00
1213  ...         NaN        NaN  47.95       0    0.0    1.0         0.00

      ICULOS  Patient_id  time
3991       1         108     0
3992       2         108     1
3993       3         108     2
3994       4         108     3
3995       5         108     4
...      ...         ...   ...
1209       7          27     5
1210       8          27     6
1211       9          27     7
1212      10          27     8
1213      11          27     9

[634 rows x 42 columns]
(1182, 42)Y test shape:
 (634, 2)
     Patient_id SepsisLabel
3991        108           0
3992        108           0
3993        108           0
3994        108           0
3995        108           0
...         ...         ...
1209         27           0
1210         27           0
1211         27           0
1212         27           0
1213         27           0

[634 rows x 2 columns]
         HR  O2Sat   Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
2264    NaN    NaN    NaN    NaN    NaN   NaN   NaN    NaN         NaN   NaN
2265   71.0   98.5    NaN   94.5   74.0   NaN  19.5    NaN         NaN   NaN
2266   70.0   98.0    NaN   96.5   70.0   NaN  17.0    NaN         NaN   NaN
2267   71.0   98.0  35.89   98.0   71.0   NaN  20.0    NaN         NaN   NaN
2268   70.0  100.0    NaN   91.0   61.0   NaN  20.5    NaN         NaN  24.0
...     ...    ...    ...    ...    ...   ...   ...    ...         ...   ...
921    91.0   95.0  37.61  124.0   73.0  63.0  21.0    NaN         NaN   NaN
922    89.0   95.0  36.39  132.0   78.0  69.0  19.0    NaN         NaN   NaN
923   100.0    NaN  36.33  172.0  100.0  84.0  25.0    NaN         NaN   NaN
924   103.0    NaN    NaN  186.0   98.0  90.0  25.0    NaN         NaN   NaN
925   116.0   97.0  38.28  200.0  108.0  90.0  24.0    NaN         6.0   NaN

      ...  Fibrinogen  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  \
2264  ...         NaN        NaN  87.78       0    0.0    1.0       -21.04
2265  ...         NaN        NaN  87.78       0    0.0    1.0       -21.04
2266  ...         NaN        NaN  87.78       0    0.0    1.0       -21.04
2267  ...         NaN        NaN  87.78       0    0.0    1.0       -21.04
2268  ...         NaN      244.0  87.78       0    0.0    1.0       -21.04
...   ...         ...        ...    ...     ...    ...    ...          ...
921   ...         NaN        NaN  39.28       1    1.0    0.0        -0.02
922   ...         NaN        NaN  39.28       1    1.0    0.0        -0.02
923   ...         NaN        NaN  39.28       1    1.0    0.0        -0.02
924   ...         NaN        NaN  39.28       1    1.0    0.0        -0.02
925   ...         NaN        NaN  39.28       1    1.0    0.0        -0.02

      ICULOS  Patient_id  time
2264       1          59     0
2265       2          59     1
2266       3          59     2
2267       4          59     3
2268       5          59     4
...      ...         ...   ...
921      130          18   129
922      131          18   130
923      132          18   131
924      133          18   132
925      134          18   133

[1182 rows x 42 columns]
Y test shape: (1182, 2)
X_train or X_test contains NaN values, KNN/mean is performed.
     Patient_id SepsisLabel
2264         59           0
2265         59           0
2266         59           0
2267         59           0
2268         59           0
...         ...         ...
921          18           1
922          18           1
923          18           1
924          18           1
925          18           1

[1182 rows x 2 columns]
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (739, 1) 1´s in y_test SepsisLabel    40.0
dtype: float64
Time spent in  9 th Fold iteration 62.28 sec.

******************************************************************
X_train_impute or X_test_impute have all been filled

y_test size: (1182, 1) 1´s in y_test SepsisLabel    48.0
dtype: float64
Time spent in  3 th Fold iteration 64.88 sec.

******************************************************************
X_train_impute or X_test_impute have all been filled
X_train_impute or X_test_impute have all been filled

y_test size: (588, 1) 1´s in y_test SepsisLabel    9.0
dtype: float64
Time spent in  0 th Fold iteration 66.47 sec.

******************************************************************

y_test size: (744, 1) 1´s in y_test SepsisLabel    18.0
dtype: float64
Time spent in  1 th Fold iteration 66.58 sec.

******************************************************************
X_train_impute or X_test_impute have all been filled
X_train_impute or X_test_impute have all been filled

y_test size: (771, 1) 1´s in y_test SepsisLabel    37.0
dtype: float64
Time spent in  7 th Fold iteration 67.29 sec.

******************************************************************

y_test size: (896, 1) 1´s in y_test SepsisLabel    16.0
dtype: float64
Time spent in  2 th Fold iteration 67.37 sec.

******************************************************************
X_train_impute or X_test_impute have all been filled
X_train_impute or X_test_impute have all been filled

y_test size: (692, 1) 1´s in y_test SepsisLabel    29.0
dtype: float64
Time spent in  6 th Fold iteration 67.56 sec.

******************************************************************

y_test size: (660, 1) X_train_impute or X_test_impute have all been filled 1´s in y_test
SepsisLabel    10.0
dtype: float64
Time spent in  5 th Fold iteration 67.66 sec.

X_train_impute or X_test_impute have all been filled ******************************************************************


y_test size: (634, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
Time spent in  4 th Fold iteration 67.83 sec.

******************************************************************

y_test size: (687, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
Time spent in  8 th Fold iteration 67.85 sec.

******************************************************************

Evaluation parameters of the utiltiy evaluation function:
auroc of model: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
auprc of model: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
utility F1 of model: [0.0, 0.0, 0.0494, 0.05, 0.0, 0.0, 0.4444, 0.0938, 0.0, 0.0]
Utility accuracy of model: [94.39, 95.7, 74.22, 80.71, 93.38, 94.7, 94.22, 92.48, 96.65, 83.36]
Utility score of model: [-0.0923, -0.0245, -0.0215, 0.018, -0.0923, -0.021, 0.5091, 0.0725, -0.0371, -0.0562]
Positive Prediction:  [24, 14, 227, 192, 32, 25, 43, 27, 13, 83]
Accuracy model: [94.39, 95.7, 74.22, 80.71, 93.38, 94.7, 94.22, 92.48, 96.65, 83.36]
F1_score model: [0.0, 0.0, 4.94, 5.0, 0.0, 0.0, 44.44, 9.38, 0.0, 0.0]
Baseline model: [98.47, 97.58, 98.21, 95.94, 98.42, 98.48, 95.81, 95.2, 98.54, 94.59]

Total Time spent in  KFold function 68.09 sec.

In [12]:
KFold_patient(decisionTreeModel,10, 1)

K Fold of  10  folds with KNN = 1
for the 1 th iteration [ 52  95  56  36 171 178  21  86  51  37  31  77   6 137 183  83  26 170
 167 179]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.75
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (588, 1) 1´s in y_test SepsisLabel    9.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  24
Time spent in this KFold iteration 21.32 sec.

******************************************************************
for the 2 th iteration [ 75  54  33 185 161 180 139 141  28  13  49  58 146  29  20 163 176 122
  19  73]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.6
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (744, 1) 1´s in y_test SepsisLabel    18.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  14
Time spent in this KFold iteration 22.04 sec.

******************************************************************
for the 3 th iteration [102  70  50 116 182  16 194  38 112   1 159  34  12  48  81 127 184  17
 199  92]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.6
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (896, 1) 1´s in y_test SepsisLabel    16.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  227
Time spent in this KFold iteration 20.2 sec.

******************************************************************
for the 4 th iteration [ 59  71   3  68   9 200  11   4  78  23 169  97  87   5 190  89 100  32
  85  18]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.63
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (1182, 1) 1´s in y_test SepsisLabel    48.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  192
Time spent in this KFold iteration 18.06 sec.

******************************************************************
for the 5 th iteration [108 124  30 104 118 162 106  74 174  14  25   2 196 186  80  88 152  66
  63  27]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (634, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  32
Time spent in this KFold iteration 20.29 sec.

******************************************************************
for the 6 th iteration [148 145  53  76 187 160 110  67 138 192 123 134 143  39  40  62  99 158
 193 130]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.63
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (660, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  25
Time spent in this KFold iteration 20.44 sec.

******************************************************************
for the 7 th iteration [113 198 150 195 105 153 121  57 125 133  90 142 117 147 154 177 128  72
 126  64]
Time for splitting id to test: 0.07
Time for splitting id to train: 0.65
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (692, 1) 1´s in y_test SepsisLabel    29.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  43
Time spent in this KFold iteration 20.59 sec.

******************************************************************
for the 8 th iteration [136 119 103  42 151 155  91 173 168 107 115  47 166 132 197 157 181  35
  45  84]
Time for splitting id to test: 0.07
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (771, 1) 1´s in y_test SepsisLabel    37.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  27
Time spent in this KFold iteration 19.57 sec.

******************************************************************
for the 9 th iteration [165   7  60  61  46 144  43 135 109  98  82 120  94   8 188  69 129 114
 140  96]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (687, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  13
Time spent in this KFold iteration 19.69 sec.

******************************************************************
for the 10 th iteration [131 101 164 111  41 175 149  10 191  55 156  65  79 172 189  44  93  22
  24  15]
Time for splitting id to test: 0.07
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (739, 1) 1´s in y_test SepsisLabel    40.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  83
Time spent in this KFold iteration 19.12 sec.

******************************************************************
Accuracy model: [94.39, 95.7, 74.22, 80.71, 93.38, 94.7, 94.22, 92.48, 96.65, 83.36]
F1_score model: [0.0, 0.0, 4.94, 5.0, 0.0, 0.0, 44.44, 9.38, 0.0, 0.0]
Baseline model: [98.47, 97.58, 98.21, 95.94, 98.42, 98.48, 95.81, 95.2, 98.54, 94.59]

Evaluation parameters of the utiltiy evaluation function:
auroc of model: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
auprc of model: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Utility accuracy of model: [94.39, 95.7, 74.22, 80.71, 93.38, 94.7, 94.22, 92.48, 96.65, 83.36]
utility F1 of model: [0.0, 0.0, 0.0494, 0.05, 0.0, 0.0, 0.4444, 0.0938, 0.0, 0.0]
Utility score of model: [-0.0923, -0.0245, -0.0215, 0.018, -0.0923, -0.021, 0.5091, 0.0725, -0.0371, -0.0562]

Total Time spent in  KFold function 201.32 sec.

In [13]:
# print("Logistic Regression")
#KFold_patient(decisionTreeModel,10, 1)

In [14]:
# print("Decision tree")
#KFold_patient(randomForestModel,10, 2)

In [15]:
# findBestKforKNN(logisticRegressionModel,10,1,10)
# findBestKforKNN(XGBoostModel,10,110,120)

In [16]:
# findBestKforKNN(decisionTreeModel,10,1,10)
# os.system('\a')

KNN of K =  1
K Fold of  10  folds with KNN = 1
for the 1 th iteration [ 52  95  56  36 171 178  21  86  51  37  31  77   6 137 183  83  26 170
 167 179]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.63
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (588, 1) 1´s in y_test SepsisLabel    9.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  24
Time spent in this KFold iteration 19.75 sec.

******************************************************************
for the 2 th iteration [ 75  54  33 185 161 180 139 141  28  13  49  58 146  29  20 163 176 122
  19  73]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.65
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (744, 1) 1´s in y_test SepsisLabel    18.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  14
Time spent in this KFold iteration 19.56 sec.

******************************************************************
for the 3 th iteration [102  70  50 116 182  16 194  38 112   1 159  34  12  48  81 127 184  17
 199  92]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (896, 1) 1´s in y_test SepsisLabel    16.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  227
Time spent in this KFold iteration 18.95 sec.

******************************************************************
for the 4 th iteration [ 59  71   3  68   9 200  11   4  78  23 169  97  87   5 190  89 100  32
  85  18]
Time for splitting id to test: 0.07
Time for splitting id to train: 0.63
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (1182, 1) 1´s in y_test SepsisLabel    48.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  192
Time spent in this KFold iteration 17.78 sec.

******************************************************************
for the 5 th iteration [108 124  30 104 118 162 106  74 174  14  25   2 196 186  80  88 152  66
  63  27]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.58
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (634, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  32
Time spent in this KFold iteration 20.22 sec.

******************************************************************
for the 6 th iteration [148 145  53  76 187 160 110  67 138 192 123 134 143  39  40  62  99 158
 193 130]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (660, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  25
Time spent in this KFold iteration 20.29 sec.

******************************************************************
for the 7 th iteration [113 198 150 195 105 153 121  57 125 133  90 142 117 147 154 177 128  72
 126  64]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.66
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (692, 1) 1´s in y_test SepsisLabel    29.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  43
Time spent in this KFold iteration 20.6 sec.

******************************************************************
for the 8 th iteration [136 119 103  42 151 155  91 173 168 107 115  47 166 132 197 157 181  35
  45  84]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (771, 1) 1´s in y_test SepsisLabel    37.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  27
Time spent in this KFold iteration 19.37 sec.

******************************************************************
for the 9 th iteration [165   7  60  61  46 144  43 135 109  98  82 120  94   8 188  69 129 114
 140  96]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (687, 1) 1´s in y_test SepsisLabel    10.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  13
Time spent in this KFold iteration 19.31 sec.

******************************************************************
for the 10 th iteration [131 101 164 111  41 175 149  10 191  55 156  65  79 172 189  44  93  22
  24  15]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.56
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (739, 1) 1´s in y_test SepsisLabel    40.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  83
Time spent in this KFold iteration 19.2 sec.

******************************************************************
Accuracy model: [94.39, 95.7, 74.22, 80.71, 93.38, 94.7, 94.22, 92.48, 96.65, 83.36]
F1_score model: [0.0, 0.0, 4.94, 5.0, 0.0, 0.0, 44.44, 9.38, 0.0, 0.0]
Baseline model: [98.47, 97.58, 98.21, 95.94, 98.42, 98.48, 95.81, 95.2, 98.54, 94.59]

Evaluation parameters of the utiltiy evaluation function:
auroc of model: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
auprc of model: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Utility accuracy of model: [94.39, 95.7, 74.22, 80.71, 93.38, 94.7, 94.22, 92.48, 96.65, 83.36]
utility F1 of model: [0.0, 0.0, 0.0494, 0.05, 0.0, 0.0, 0.4444, 0.0938, 0.0, 0.0]
Utility score of model: [-0.0923, -0.0245, -0.0215, 0.018, -0.0923, -0.021, 0.5091, 0.0725, -0.0371, -0.0562]

Total Time spent in  KFold function 195.03 sec.

KNN of K =  6
K Fold of  10  folds with KNN = 6
for the 1 th iteration [ 52  95  56  36 171 178  21  86  51  37  31  77   6 137 183  83  26 170
 167 179]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.63
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (588, 1) 1´s in y_test SepsisLabel    9.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  26
Time spent in this KFold iteration 20.72 sec.

******************************************************************
for the 2 th iteration [ 75  54  33 185 161 180 139 141  28  13  49  58 146  29  20 163 176 122
  19  73]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (744, 1) 1´s in y_test SepsisLabel    18.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  30
Time spent in this KFold iteration 20.03 sec.

******************************************************************
for the 3 th iteration [102  70  50 116 182  16 194  38 112   1 159  34  12  48  81 127 184  17
 199  92]
Time for splitting id to test: 0.07
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.
X_train_impute or X_test_impute have all been filled

y_test size: (896, 1) 1´s in y_test SepsisLabel    16.0
dtype: float64
The number of 1 (SepsisLabel) in this prediction:  211
Time spent in this KFold iteration 20.48 sec.

******************************************************************
for the 4 th iteration [ 59  71   3  68   9 200  11   4  78  23 169  97  87   5 190  89 100  32
  85  18]
Time for splitting id to test: 0.06
Time for splitting id to train: 0.62
X_train or X_test contains NaN values, KNN/mean is performed.

KeyboardInterrupt:

In [ ]:
displayCurrentResult(1,9)